# Generated by Django 6.1 on 2026-09-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('risk_points', models.IntegerField()),
                ('description', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
            ],
        ),
    ]
