# Generated by Django 6.1 on 2026-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_scan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
