# Generated by Django 6.1 on 2026-09-25 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_finding_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='security_score',
        ),
        migrations.AddField(
            model_name='finding',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='product',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='finding',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scan',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='status',
            field=models.CharField(default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='finding',
            name='risk_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
