# Generated by Django 6.1 on 2026-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_remove_scan_security_score_finding_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='web_scan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
