# Generated by Django 6.1 on 2026-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_scan_web_scan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='tls_scan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
