# Generated by Django 6.1 on 2026-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scan_tls_scan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='security_intelligence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
