# Generated by Django 6.1 on 2026-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_finding_security_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cve_intelligence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
